logo_team_lookup = {
    'BRO': 'Broncos',
    'NZL': 'Warriors',
    'GCT': 'Titans',
    'NEW': 'Knights',
    'WST': 'Tigers',
    'SYD': 'Roosters',
    'STG': 'Dragons',
    'STH': 'Rabbitohs',
    'PTH': 'Panthers',
    'PAR': 'Eels',
    'NQC': 'Cowboys',
    'MEL': 'Storm',
    'MNL': 'Sea Eagles',
    'DOL': 'Dolphins',
    'SHA': 'Sharks',
    'BUL': 'Bulldogs',
    'CBR': 'Raiders'
}

map_col_names = {
    'TEAM':'team',
    'SEASON':'season',
    'RND':'round',
    'OPPONENT':'opponent',
    'BE':'break_even',
    'FANTASY':'fantasy_points',
    'PRICE':'price',
    'POSITION':'position',
    'MINS':'minutes_played',
    'T':'tries',
    'TS':'try_saves',
    'G':'goals',
    'FG':'field_goals',
    'TA':'try_assists',
    'LB':'line_breaks',
    'LBA':'line_break_assists',
    'TCK':'tackles',
    'TB':'tackle_breaks',
    'MT':'missed_tackles',
    'OF':'offloads',
    'OFH':'offloads_hand',
    'OFG':'offloads_ground',
    'ER':'errors',
    'TO':'turnovers',
    'MG':'meters_gained',
    'KM':'kick_meters',
    'KD':'kicks_defused',
    'PC':'penalties_conceded',
    'SB':'sinbin',
    'SO':'send_off',
    'FDO':'forced_dropout',
    'PLAYER':'player'
}
